# Generated by Django 3.1.6 on 2021-04-09 16:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('class_rank', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Four Year'), ('G', 'Graduate Student'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('major', models.CharField(blank=True, max_length=50)),
                ('picture', models.ImageField(default='default.jpg', upload_to='profile_pictures')),
                ('description', models.TextField(blank=True, max_length=300)),
                ('roommates', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('semesters', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('bedtime', models.TimeField(default=datetime.time(0, 0))),
                ('politics', models.CharField(choices=[('L', 'Liberal'), ('M', 'Moderate'), ('C', 'Conservative'), ('U', 'Prefer not to say')], default='U', max_length=1)),
                ('tidiness_factor', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('party_factor', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('guest_factor', models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
