# Generated by Django 3.1.6 on 2021-04-28 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Search Latitude'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Search Longitude'),
        ),
        migrations.AddField(
            model_name='profile',
            name='search_radius',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Search Radius'),
        ),
    ]
