language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: wWGD+v+BZMGYd+YXnWp74PGj/H34fvl4g+BOM1KmpMEZa9pQXwkUQltnlJbsQ5IfkmbdB+XYuOwl4jMZObpwbkyF1iYckAthMHqdpBuxgI1Ynb5CEoFNqqCB6fbVTT3LnDB5sQSoNLvlfWMq5STAaE1Q+eH4HMcm6rEUEkY78BPFk8ZkNB70U0HfVSShOSGBAIQGbExurMM38k29MnThNeln+q00/WL/fco0sDyT15A5OqS4jYlFcReQ8e1fzA4cnmYThlTZWEOrUwZmrKGD7nnO1zOuIdCGS0QWZ8B9iObtyfSO25/LSRWmi2PzPkjnix9xSQnbOFlW7uORQ4OB+w7qGUASf+ObTjJ3U1Wd64a1RZVH2JBhM1S6Jp+nLl6nKhhN+E/94eoK153YvAV2X8KG7wJx97Cm3zsFElooSPNJAJko1DE/BIlpJDWlN9ied+h6fffywFBn8+6BRDM8SHxHbPp/MlOxhdxu1e4HoPbj/tbsrcJyp7iAGIznklRQ88RwTLi+bj++9FRtLkkulxqx4o06fZEg0hOZFtN91m98j5lt85jhdUXBbiqvygh00gOrOpnmwRml65MpMvaqsDMA/Eam4M/jAbM1VgxSDzER47LpZSGCs9LHg7Ca7j2KUPSnrvy/Cf2/zJIv0eBh0UDYY/Tpd8AcRAymn/OvL94=
  app: netconnect
  on:
    repo: uva-cs3240-s21/project-b-20
